name: My PipePlan

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Build
        run: dotnet build

  test:
    runs-on: ubuntu-latest
    needs: build  # –ñ–¥–µ—Ç –∑–∞–≤–µ—Ä—à–µ–Ω–∏—è build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Test
        run: dotnet test

  deployment:
    runs-on: ubuntu-latest
    needs: test  # –ñ–¥–µ—Ç –∑–∞–≤–µ—Ä—à–µ–Ω–∏—è test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Deployment
        run: dotnet publish -c Release -o ./publish
      
      - name: Show result
        run: echo "üéâ Deployment completed!"